# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CYYActionSheetDemo' do
pod 'Masonry'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CYYActionSheetDemo

  target 'CYYActionSheetDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CYYActionSheetDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
